### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by AlexanderNv** [smirkingman/RealSense-Calibrator#3]
I get the following errors when I try to run the tool, the first seems to generally popup when launching it after plugging in the device. The second one on further attempts. Device firmware is the latest and at any point in the testing process the realsense viewer seems to work properly.

![error2](https://user-images.githubusercontent.com/22816903/48940601-956cf700-ef18-11e8-86a0-dab31e0ef3f1.PNG)

![error1](https://user-images.githubusercontent.com/22816903/48940609-9c940500-ef18-11e8-991c-ebdcb9d64851.PNG)

**Comment by MauriceCalvert** [comment]
It seems that it can't get the backlight option. Which camera are you using? I only have D435s so I haven't been able to test with other models.

Suggestion: Run in Debug, breakpoint on exceptions, to see exactly what the missing object reference is referring to. I don't seem to be getting emails from GitHub when you post, feel free to contact me directly:
maurice AT calvert DOT ch

**Comment by MauriceCalvert** [comment]
I have updated the repository to fix this
