### ISSUE TITLE
Side by Side Configuration Incorrect

### ISSUE THREAD

**Issue by playwithtechnology** [smirkingman/RealSense-Calibrator#4]
I read your paper and decided to give your calibration tool a go. Unfortunately, once everything is pulled and in a folder, and I go to launch UI.exe I get an error that reads 

"
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more details.
"

Usually that is a non included in project, dependency error. I did verify same result on two separate machines, any thoughts?

**Comment by MauriceCalvert** [comment]
I have updated the repository, can you try again with the latest version?

**Comment by playwithtechnology** [comment]
Can you update release? I just started reinstalling my computer and will be a bit until I get VS reinstalled.

**Comment by MauriceCalvert** [comment]
Sorry, I don't understand. I have updated the project on Git

**Comment by MauriceCalvert** [comment]
I have added the Debug compilation to faciltate error diagnosis
