### ISSUE TITLE
Calibration results are not input in Realsense

### ISSUE THREAD

**Issue by yama104** [smirkingman/RealSense-Calibrator#5]
I am using your calibrator for making high accuracy realsense at about 3.0 meter.
but realsense accuracy is not changed after calibration.
I couldn't find the hint for cause.
please check the below status and tell me how to analysis or cause.

Problem :  Calibration results are not input in Realsense
Realsense device :  D435
farmware version :  5.11.01.100
SDK version in Windows PC : 2.17.0
Calibrator version : latest (and use "Debug" not "Release")

Procedure:  
    1. check the realsense accuracy in realsense viewer => error is -3~40 cm at 3 meter
    2. calibrate realsense follow your procedure to range 3000mm
    3. check the realsense accuracy same as 1 => but no change

Analysis:   - Log : no irregular happen.

Attachment : my calibration output file
[435-calibration_result.zip](https://github.com/smirkingman/RealSense-Calibrator/files/4069953/435-calibration_result.zip)

I couldn't get more information
if something to check, please help me.

thank you

**Comment by MauriceCalvert** [comment]
My program calculates the geometry of a RealSense camera, which you then use to correct the depth data. It DOES NOT change anything the camera itself. 

Your calibration looks good (for example, your depth focal point - the value C - is 26.01mm behind the front glass, which sounds right). 

What you need to do now is to correct your depth values in your application, using the example https://www.calvert.ch/download/realsensecalibrator/analysingresults.html

In-depth discussion here https://www.calvert.ch/maurice/2018/11/01/realsense-cameras-calculating-3d-coordinates-from-depth-row-and-column/

**Comment by yama104** [comment]
Thank you for reply.
Sorry, I misunderstood.
I got it now.
Your calibrator measure and output calibration parameter.
I will try another way like your writing.

but I have a question about that.
if depth image size is not 848x480, can I change it ?

**Comment by MauriceCalvert** [comment]
Yes, the calibration parameters can be applied at any resolution.
The only constraint is that the depth and colour streams MUST be at the SAME resolution, and I strongly recommend that you calibrate at the resolution that you'll be using in your application:
![image](https://user-images.githubusercontent.com/22235329/72754699-d9b16100-3bc8-11ea-9318-ae20c148f23e.png)
